export {default as Navbar} from './Navbar';
export {default as  Feed} from './Feed';
export {default as ChannelDetail} from './ChannelDetail';
export {default as VedioDetail} from './VedioDetail';
export {default as SearchFeed} from './SearchFeed';
export { default as SearchBar } from './SearchBar';
export { default as Sidebar } from './Sidebar';
export { default as Vedios } from './Vedios';
export { default as ChannelCard } from './ChannelCard';
export { default as VedioCard } from './VedioCard';
// import {Navbar} from './components/Navbar';
// import {Feed} from './components/Feed';
// import {ChannelDetail} from './components/ChannelDetail';
// import {VedioDetail} from './components/VedioDetail';
// import {SearchFeed} from './components/SearchFeed';